//      Copyright (c) Microsoft Corporation. All rights reserved.
// SideShowBitmapDriver
// NoDevice

import "wudfddi.idl";

[
    uuid(a0c7c69c-99e8-4840-924e-b01393b288e6),
    version(1.0),
    helpstring("Windows SideShow Bitmap Driver 1.0 Type Library")
]
library AuxDriverLib
{
    importlib("stdole2.tlb");
    [
        uuid(b748f9f9-679a-451a-bf61-2b35489293a0),
        helpstring("WSSBasicDisplayDriver Class")
    ]
    coclass WSSDisplayDriver
    {
        [default] interface IDriverEntry;
    };
};

